# fly.toml app configuration file generated for khamiruf-withered-hill-6930 on 2025-04-07T00:04:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'khamiruf-withered-hill-6930'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
